
spring:
  datasource:
    name: medicine
    password: 123456
    url: jdbc:mysql://192.168.0.188/medicine?serverTimezone=GMT&characterEncoding=utf-8
    username: xiong
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  resources:
    #前端访问的静态文件路径中加了一级static目录，所以这边不能用默认的static目录
    static-locations: classpath:/
mybatis:
  # model的包
  type-aliases-package: com.example.medicine.bean
  mapper-locations: classpath:mapper/*.xml

